version: '3'

services:
  backend:
    image: 'backend'
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/hospitalReport_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234567890
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - "5440:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234567890
      - POSTGRES_DB=hospitalReport_db
  frontend:
      image: 'frontend'
      build: ./frontend
      container_name: 'frontend'
      ports:
        - "3000:3000"
      depends_on:
      - backend

